# params.yaml
data_preprocessing:
  test_size: 0.2
  random_state: 42

train:
  random_state: 42
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  model_path: saved_models/model.joblib

evaluate:
  metrics_file: metrics.json
